--CREATE DATABASE Pirates
--go
USE Pirates
--CREATE TABLE Ships
--(
--	Id INT IDENTITY PRIMARY KEY,
--	[Name] VARCHAR(21) NOT NULL,
--	Capacity INT NOT NULL,
--	Constructed DATE NOT NULL,
--	Price DECIMAL(18, 2) NOT NULL
--)
CREATE TABLE Berths
(
	Number CHAR(4) PRIMARY KEY
)